import type { Analysis } from '@/types/database'
import type { AnalysisResult } from '@/types/analysis'
import { getScoreLabel } from './utils'

export function generateReportHtml(analysis: Analysis, result: AnalysisResult): string {
  const score = analysis.ats_score ?? 0
  const scoreColor = score >= 80 ? '#22c55e' : score >= 60 ? '#eab308' : score >= 40 ? '#f97316' : '#ef4444'

  const categoryRows = [
    ['Keywords Match', result.categories.keywordsMatch.score],
    ['Format & Structure', result.categories.formatStructure.score],
    ['Experience Relevance', result.categories.experienceRelevance.score],
    ['Skills Alignment', result.categories.skillsAlignment.score],
    ['Impact Statements', result.categories.impactStatements.score],
  ]

  const recommendationsHtml = result.recommendations
    .sort((a, b) => ({ high: 0, medium: 1, low: 2 }[a.impact] - { high: 0, medium: 1, low: 2 }[b.impact]))
    .map(r => `
      <div style="margin-bottom: 16px; padding: 12px; border-left: 3px solid ${r.impact === 'high' ? '#ef4444' : r.impact === 'medium' ? '#eab308' : '#3b82f6'}; background: #f8fafc;">
        <div style="font-weight: 600; margin-bottom: 4px; font-size: 13px;">[${r.impact.toUpperCase()}] ${r.title}</div>
        <div style="color: #475569; font-size: 12px; margin-bottom: 6px;">${r.description}</div>
        <div style="font-size: 12px;"><strong>Action:</strong> ${r.actionItem}</div>
      </div>
    `).join('')

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>ResuLift Analysis Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #0f172a; margin: 0; padding: 0; background: white; }
  .page { max-width: 700px; margin: 0 auto; padding: 40px; }
  h2 { font-size: 16px; font-weight: 700; margin: 24px 0 12px; color: #1e293b; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; }
  td, th { padding: 8px 12px; text-align: left; font-size: 13px; }
  tr:nth-child(even) { background: #f8fafc; }
</style>
</head>
<body>
<div class="page">
  <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px;">
    <div>
      <div style="font-size: 24px; font-weight: 800; color: #7c3aed; margin-bottom: 4px;">ResuLift</div>
      <div style="color: #64748b; font-size: 13px;">ATS Resume Analysis Report</div>
    </div>
    <div style="text-align: right; font-size: 12px; color: #94a3b8;">
      <div>${new Date(analysis.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
      <div style="text-transform: capitalize;">${analysis.type} Analysis</div>
    </div>
  </div>

  ${analysis.job_title ? `<div style="margin-bottom: 24px;"><strong>Position:</strong> ${analysis.job_title}${analysis.job_company ? ` at ${analysis.job_company}` : ''}</div>` : ''}

  <div style="text-align: center; padding: 24px; background: #f8fafc; border-radius: 12px; margin-bottom: 32px;">
    <div style="font-size: 64px; font-weight: 800; color: ${scoreColor}; line-height: 1;">${score}</div>
    <div style="color: #64748b; margin-top: 4px;">ATS Score — ${getScoreLabel(score)}</div>
    <p style="color: #475569; font-size: 13px; margin-top: 12px; max-width: 500px; margin-left: auto; margin-right: auto;">${result.summary}</p>
  </div>

  <h2>Category Breakdown</h2>
  <table>
    <thead><tr><th style="background: #1e293b; color: white;">Category</th><th style="background: #1e293b; color: white;">Score</th></tr></thead>
    <tbody>
      ${categoryRows.map(([name, s]) => `<tr><td>${name}</td><td><strong>${s}/100</strong></td></tr>`).join('')}
    </tbody>
  </table>

  <h2>Recommendations</h2>
  ${recommendationsHtml}

  ${analysis.type === 'premium' && result.optimizedBulletPoints?.length ? `
  <h2>Optimized Bullet Points</h2>
  ${result.optimizedBulletPoints.map((b, i) => `
    <div style="margin-bottom: 16px; padding: 12px; border: 1px solid #e2e8f0; border-radius: 8px;">
      <div style="font-size: 11px; color: #94a3b8; margin-bottom: 4px;">ORIGINAL</div>
      <div style="font-size: 12px; color: #475569; margin-bottom: 8px;">${b.original}</div>
      <div style="font-size: 11px; color: #7c3aed; margin-bottom: 4px;">OPTIMIZED</div>
      <div style="font-size: 12px; font-weight: 500;">${b.optimized}</div>
    </div>
  `).join('')}
  ` : ''}

  <div style="margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 11px; color: #94a3b8;">
    Generated by ResuLift • ${process.env.NEXT_PUBLIC_APP_URL}
  </div>
</div>
</body>
</html>`
}
